<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>edu.uci.dce.x46017</groupId>
    <artifactId>uci-java-programming-codespaces</artifactId>
    <version>1.0.0</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>

  <artifactId>01-assignments-student</artifactId>

  <build>
    <sourceDirectory>src</sourceDirectory>
    <resources>
      <resource><directory>resources</directory></resource>
    </resources>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.mariadb.jdbc</groupId>
      <artifactId>mariadb-java-client</artifactId>
      <version>3.5.9</version>
    </dependency>
  </dependencies>
</project>
